title: Benevolent Tech
url: "https://benevolent.tech"
baseurl:
google_maps_javascript_api_key: AIzaSyDKMKUAB7EOak_dTHHeUX8N0MNuYRFh_Ik
disqus_shortname: benevolenttech

# Default description in social shares for the jekyll-seo-tag gem
description: We are a DC-based online marketing and web development agency that helps small businesses grow their business.

# Author details for the jekyll-seo-tag gem
author:
  name: Benevolent Tech
  email: hi@benevolent.tech
  twitter: benevolentweb # twitter username without the @ symbol

# Social details for the jekyll-seo-tag gem
social:
  name: Benevolent Tech
  links:
    - https://twitter.com/benevolentweb

collections:
  staff_members:
    output: false
  clients:
    output: false

permalink: /posts/:title.html

# These are for paginate v1
# paginate: 6
# paginate_path: "/learning/:num/"

pagination:
  
  # Site-wide kill switch, disabled here it doesn't run at all 
  enabled: true

  # Set to 'true' to enable pagination debugging. This can be enabled in the site config or only for individual pagination pages
  debug: false

  # How many objects per paginated page, used to be `paginate` (default: 0, means all)
  per_page: 6

  # The permalink structure for the paginated pages (this can be any level deep)
  permalink: '/page/:num/' # Pages are index.html inside this folder (default)
  #permalink: '/page/:num.html' # Pages are simple html files 
  #permalink: '/page/:num' # Pages are html files, linked jekyll extensionless permalink style.

  # Limit how many pagenated pages to create (default: 0, means all)
  limit: 0
  
  # Optional, defines the field that the posts should be sorted on (omit to default to 'date')
  sort_field: 'date'

  # Optional, sorts the posts in reverse order (omit to default decending or sort_reverse: true)
  sort_reverse: true


jekyll-archives:
  enabled:
    - "categories"
  layout: 'category'

algolia:
  application_id: 'MUZJLD13O2'
  index_name:     'Benevolent Tech Main'
  record_css_selector: 'p,ul,ol,h1,h2,h3,h4,h5'
  settings:
      attributesToIndex:
        - title
        - h1
        - h2
        - h3
        - h4
        - h5
        - h6
        - unordered(text)
        - unordered(tags)
        - ul
        - ol
  excluded_files:
      - seo-starter-spreadsheet-success.html
      - newsletter-success.html

gems:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate-v2
  - jekyll-archives
  - jekyll-sitemap
  - jekyll-mentions
  - algoliasearch-jekyll


exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENCE
  - node_modules
  - gulpfile.js

jekyll-mentions:
  base_url: https://twitter.com


defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "clients"
    values:
      layout: "client"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  - scope:
      path: "index.html"
      type: "pages"
    values:
      layout: "default"

# -----------
# CloudCannon

social_icons:
  - Facebook
  - Google Plus
  - Instagram
  - LinkedIn
  - Pinterest
  - Tumblr
  - Twitter
  - YouTube
  - RSS
