title: Benevolent Tech
url: "https://benevolent.tech"
baseurl:
google_analytics_key: UA-80397803-1
google_maps_javascript_api_key: AIzaSyDKMKUAB7EOak_dTHHeUX8N0MNuYRFh_Ik
disqus_shortname: benevolenttech

# Default description in social shares for the jekyll-seo-tag gem
description: A group of friends with technical and emotional depth with an altruistic mission, here to help you catch up to the future.

# Author details for the jekyll-seo-tag gem
author:
  name: Benevolent Tech
  email: hi@benevolent.tech
  twitter: benevolentweb # twitter username without the @ symbol

# Social details for the jekyll-seo-tag gem
social:
  name: Benevolent Tech
  links:
    - https://twitter.com/benevolentweb

collections:
  staff_members:
    output: false
  clients:
    output: false

paginate: 10
paginate_path: "/learning-center/:num/"
permalink: pretty

jekyll-archives:
  enabled:
    - "categories"

gems:
  - "jekyll-feed"
  - "jekyll-seo-tag"
  - "jekyll-paginate"
  - "jekyll-archives"

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "clients"
    values:
      layout: "client"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  - scope:
      path: "index.html"
      type: "pages"
    values:
      layout: "default"

# -----------
# CloudCannon

social_icons:
  - Facebook
  - Google Plus
  - Instagram
  - LinkedIn
  - Pinterest
  - Tumblr
  - Twitter
  - YouTube
  - RSS
